"""Add FinOps fields

Revision ID: f4fbc65bd6da
Revises: 976d87809f03
Create Date: 2026-04-02 17:05:18.362794

"""

from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op  # type: ignore[attr-defined]

# revision identifiers, used by Alembic.
revision: str = "f4fbc65bd6da"
down_revision: Union[str, Sequence[str], None] = "976d87809f03"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agents", sa.Column("monthly_budget_usd", sa.Float(), nullable=True))
    op.add_column("audit_logs", sa.Column("cost_usd", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("audit_logs", "cost_usd")
    op.drop_column("agents", "monthly_budget_usd")
    # ### end Alembic commands ###
